/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GuruController;
import database.Database;
import event.GuruListener;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.GuruModel;
import table.GuruTableModel;

/**
 *
 * @author tsisw
 */
public class MainView extends javax.swing.JFrame {

    GuruEditView guruEdit;
    GuruTableModel guruTableModel;
    Database db;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);

        tampilGuru();
    }

    private GuruModel model;
    private GuruController controller;

    private void tampilGuru() {
        db = new Database();
        guruTableModel = new GuruTableModel();
        guruTableModel.setData(db.tampil_semua_GuruModel());
        tblGuru.setModel(guruTableModel);
    }

    private void refreshGuru() {
        guruTableModel.setData(db.tampil_semua_GuruModel());
        guruTableModel.fireTableDataChanged();
        tblGuru.changeSelection(0, 0, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btn_menu_pelajaran = new javax.swing.JButton();
        btn_menu_guru1 = new javax.swing.JButton();
        btn_menu_tingkat1 = new javax.swing.JButton();
        btn_menu_siswa = new javax.swing.JButton();
        btn_menu_orangtua = new javax.swing.JButton();
        btn_menu_kelas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_menu_beranda = new javax.swing.JButton();
        btn_menu_tentangKami = new javax.swing.JButton();
        btn_menu_keluar = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        berandaPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        guruPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_guru_tambah_div = new javax.swing.JPanel();
        btn_guru_tambah = new javax.swing.JLabel();
        btn_guru_refresh = new javax.swing.JButton();
        btn_guru_edit = new javax.swing.JButton();
        btn_guru_hapus = new javax.swing.JButton();
        tf_guru_cari = new javax.swing.JTextField();
        btn_guru_cari = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuru = new javax.swing.JTable();
        tingkatPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pelajaranPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        siswaPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        orangTuaPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        kelasPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Sekolah ");
        setPreferredSize(new java.awt.Dimension(1200, 700));

        bodyPanel.setBackground(new java.awt.Color(236, 240, 241));
        bodyPanel.setPreferredSize(new java.awt.Dimension(1200, 700));

        menuPanel.setBackground(new java.awt.Color(41, 128, 185));

        btn_menu_pelajaran.setBackground(new java.awt.Color(41, 128, 185));
        btn_menu_pelajaran.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_menu_pelajaran.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_pelajaran.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\icons8-book-32.png")); // NOI18N
        btn_menu_pelajaran.setText("Pelajaran");
        btn_menu_pelajaran.setBorder(null);
        btn_menu_pelajaran.setContentAreaFilled(false);
        btn_menu_pelajaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu_pelajaran.setIconTextGap(16);
        btn_menu_pelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_pelajaranActionPerformed(evt);
            }
        });

        btn_menu_guru1.setBackground(new java.awt.Color(41, 128, 185));
        btn_menu_guru1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_menu_guru1.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_guru1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\icons8-ios-32.png")); // NOI18N
        btn_menu_guru1.setText("Guru");
        btn_menu_guru1.setBorder(null);
        btn_menu_guru1.setContentAreaFilled(false);
        btn_menu_guru1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu_guru1.setIconTextGap(16);
        btn_menu_guru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_guru1ActionPerformed(evt);
            }
        });

        btn_menu_tingkat1.setBackground(new java.awt.Color(41, 128, 185));
        btn_menu_tingkat1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_menu_tingkat1.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_tingkat1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\icons8-stairs-up-32.png")); // NOI18N
        btn_menu_tingkat1.setText("Tingkat");
        btn_menu_tingkat1.setBorder(null);
        btn_menu_tingkat1.setContentAreaFilled(false);
        btn_menu_tingkat1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu_tingkat1.setIconTextGap(16);
        btn_menu_tingkat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_tingkat1ActionPerformed(evt);
            }
        });

        btn_menu_siswa.setBackground(new java.awt.Color(41, 128, 185));
        btn_menu_siswa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_menu_siswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_siswa.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\icons8-student-male-32.png")); // NOI18N
        btn_menu_siswa.setText("Siswa");
        btn_menu_siswa.setBorder(null);
        btn_menu_siswa.setContentAreaFilled(false);
        btn_menu_siswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu_siswa.setIconTextGap(16);
        btn_menu_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_siswaActionPerformed(evt);
            }
        });

        btn_menu_orangtua.setBackground(new java.awt.Color(41, 128, 185));
        btn_menu_orangtua.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_menu_orangtua.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_orangtua.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\icons8-guardian-32.png")); // NOI18N
        btn_menu_orangtua.setText("Orang Tua Siswa");
        btn_menu_orangtua.setBorder(null);
        btn_menu_orangtua.setContentAreaFilled(false);
        btn_menu_orangtua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu_orangtua.setIconTextGap(16);
        btn_menu_orangtua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_orangtuaActionPerformed(evt);
            }
        });

        btn_menu_kelas.setBackground(new java.awt.Color(41, 128, 185));
        btn_menu_kelas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_menu_kelas.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_kelas.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\icons8-google-classroom-32.png")); // NOI18N
        btn_menu_kelas.setText("Kelas");
        btn_menu_kelas.setBorder(null);
        btn_menu_kelas.setContentAreaFilled(false);
        btn_menu_kelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu_kelas.setIconTextGap(16);
        btn_menu_kelas.setSelected(true);
        btn_menu_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_kelasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\icons8-school-50.png")); // NOI18N
        jLabel1.setText("Sekolah Apps");
        jLabel1.setIconTextGap(24);

        btn_menu_beranda.setBackground(new java.awt.Color(41, 128, 185));
        btn_menu_beranda.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_menu_beranda.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_beranda.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\icons8-google-classroom-32.png")); // NOI18N
        btn_menu_beranda.setText("Beranda");
        btn_menu_beranda.setBorder(null);
        btn_menu_beranda.setContentAreaFilled(false);
        btn_menu_beranda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu_beranda.setIconTextGap(16);
        btn_menu_beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_berandaActionPerformed(evt);
            }
        });

        btn_menu_tentangKami.setBackground(new java.awt.Color(41, 128, 185));
        btn_menu_tentangKami.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_menu_tentangKami.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_tentangKami.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\provis_sekolah\\icons8-info-32.png")); // NOI18N
        btn_menu_tentangKami.setText("Tentang Kami");
        btn_menu_tentangKami.setBorder(null);
        btn_menu_tentangKami.setContentAreaFilled(false);
        btn_menu_tentangKami.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu_tentangKami.setIconTextGap(16);
        btn_menu_tentangKami.setSelected(true);
        btn_menu_tentangKami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_tentangKamiActionPerformed(evt);
            }
        });

        btn_menu_keluar.setBackground(new java.awt.Color(41, 128, 185));
        btn_menu_keluar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_menu_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_keluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\provis_sekolah\\icons8-exit-32.png")); // NOI18N
        btn_menu_keluar.setText("Keluar");
        btn_menu_keluar.setBorder(null);
        btn_menu_keluar.setContentAreaFilled(false);
        btn_menu_keluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu_keluar.setIconTextGap(16);
        btn_menu_keluar.setSelected(true);
        btn_menu_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_menu_pelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_menu_tingkat1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_menu_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_menu_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_menu_orangtua, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_menu_beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_menu_guru1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_menu_tentangKami, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menu_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_menu_beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_guru1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_tingkat1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_pelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_orangtua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_tentangKami, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_menu_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(236, 240, 241));
        mainPanel.setPreferredSize(new java.awt.Dimension(940, 706));
        mainPanel.setLayout(new java.awt.CardLayout());

        berandaPanel.setBackground(new java.awt.Color(236, 240, 241));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText("Beranda");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addContainerGap(1621, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout berandaPanelLayout = new javax.swing.GroupLayout(berandaPanel);
        berandaPanel.setLayout(berandaPanelLayout);
        berandaPanelLayout.setHorizontalGroup(
            berandaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, berandaPanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        berandaPanelLayout.setVerticalGroup(
            berandaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berandaPanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(638, Short.MAX_VALUE))
        );

        mainPanel.add(berandaPanel, "card2");

        guruPanel.setBackground(new java.awt.Color(236, 240, 241));
        guruPanel.setPreferredSize(new java.awt.Dimension(946, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("Guru");

        btn_guru_tambah_div.setBackground(new java.awt.Color(41, 128, 185));
        btn_guru_tambah_div.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_guru_tambah_div.setPreferredSize(new java.awt.Dimension(120, 40));
        btn_guru_tambah_div.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_guru_tambah_divMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_guru_tambah_divMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_guru_tambah_divMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_guru_tambah_divMouseReleased(evt);
            }
        });

        btn_guru_tambah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_guru_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_guru_tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_guru_tambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\provis_sekolah\\icons8-plus-math-16.png")); // NOI18N
        btn_guru_tambah.setText("Tambah Guru");
        btn_guru_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guru_tambah.setPreferredSize(new java.awt.Dimension(120, 17));
        btn_guru_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guru_tambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_guru_tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_guru_tambahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_guru_tambahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_guru_tambahMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn_guru_tambah_divLayout = new javax.swing.GroupLayout(btn_guru_tambah_div);
        btn_guru_tambah_div.setLayout(btn_guru_tambah_divLayout);
        btn_guru_tambah_divLayout.setHorizontalGroup(
            btn_guru_tambah_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_guru_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
        btn_guru_tambah_divLayout.setVerticalGroup(
            btn_guru_tambah_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_guru_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btn_guru_refresh.setBackground(new java.awt.Color(255, 255, 255));
        btn_guru_refresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\provis_sekolah\\icons8-refresh-24.png")); // NOI18N
        btn_guru_refresh.setToolTipText("Segarkan");
        btn_guru_refresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(39, 174, 96), new java.awt.Color(39, 174, 96), new java.awt.Color(39, 174, 96), new java.awt.Color(39, 174, 96)));
        btn_guru_refresh.setContentAreaFilled(false);
        btn_guru_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guru_refresh.setPreferredSize(new java.awt.Dimension(73, 40));
        btn_guru_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guru_refreshActionPerformed(evt);
            }
        });

        btn_guru_edit.setBackground(new java.awt.Color(211, 84, 0));
        btn_guru_edit.setForeground(new java.awt.Color(41, 128, 185));
        btn_guru_edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\provis_sekolah\\icons8-edit-property-24.png")); // NOI18N
        btn_guru_edit.setText("Edit");
        btn_guru_edit.setToolTipText("Klik datanya, kemudian klik edit");
        btn_guru_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(41, 128, 185), new java.awt.Color(41, 128, 185), new java.awt.Color(41, 128, 185), new java.awt.Color(41, 128, 185)));
        btn_guru_edit.setContentAreaFilled(false);
        btn_guru_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guru_edit.setIconTextGap(8);
        btn_guru_edit.setOpaque(false);
        btn_guru_edit.setPreferredSize(new java.awt.Dimension(73, 40));
        btn_guru_edit.setSelected(true);
        btn_guru_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guru_editActionPerformed(evt);
            }
        });

        btn_guru_hapus.setForeground(new java.awt.Color(192, 57, 43));
        btn_guru_hapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\provis_sekolah\\icons8-trash-can-24.png")); // NOI18N
        btn_guru_hapus.setText("Hapus");
        btn_guru_hapus.setToolTipText("Klik datanya, kemudian klik hapus");
        btn_guru_hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(192, 57, 43), new java.awt.Color(192, 57, 43), new java.awt.Color(192, 57, 43), new java.awt.Color(192, 57, 43)));
        btn_guru_hapus.setContentAreaFilled(false);
        btn_guru_hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guru_hapus.setPreferredSize(new java.awt.Dimension(73, 40));
        btn_guru_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guru_hapusActionPerformed(evt);
            }
        });

        tf_guru_cari.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tf_guru_cari.setToolTipText("");
        tf_guru_cari.setBorder(null);
        tf_guru_cari.setPreferredSize(new java.awt.Dimension(59, 40));

        btn_guru_cari.setBackground(new java.awt.Color(142, 68, 173));
        btn_guru_cari.setIcon(new javax.swing.ImageIcon("C:\\Users\\tsisw\\Downloads\\Icons\\provis_sekolah\\icons8-search-24.png")); // NOI18N
        btn_guru_cari.setBorder(null);
        btn_guru_cari.setContentAreaFilled(false);
        btn_guru_cari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guru_cari.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_guru_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guru_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tf_guru_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guru_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2))
                .addGap(46, 46, 46)
                .addComponent(btn_guru_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_guru_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_guru_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_guru_tambah_div, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_guru_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_guru_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_guru_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(btn_guru_tambah_div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_guru_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_guru_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        tblGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Guru", "Nama", "E-mail", "Tanggal Lahir", "Telepon", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGuru);

        javax.swing.GroupLayout guruPanelLayout = new javax.swing.GroupLayout(guruPanel);
        guruPanel.setLayout(guruPanelLayout);
        guruPanelLayout.setHorizontalGroup(
            guruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guruPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(859, Short.MAX_VALUE))
            .addGroup(guruPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        guruPanelLayout.setVerticalGroup(
            guruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guruPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        mainPanel.add(guruPanel, "card3");

        tingkatPanel.setBackground(new java.awt.Color(236, 240, 241));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Tingkat");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(1634, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tingkatPanelLayout = new javax.swing.GroupLayout(tingkatPanel);
        tingkatPanel.setLayout(tingkatPanelLayout);
        tingkatPanelLayout.setHorizontalGroup(
            tingkatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tingkatPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tingkatPanelLayout.setVerticalGroup(
            tingkatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tingkatPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(635, Short.MAX_VALUE))
        );

        mainPanel.add(tingkatPanel, "card4");

        pelajaranPanel.setBackground(new java.awt.Color(236, 240, 241));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Pelajaran");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addContainerGap(1608, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pelajaranPanelLayout = new javax.swing.GroupLayout(pelajaranPanel);
        pelajaranPanel.setLayout(pelajaranPanelLayout);
        pelajaranPanelLayout.setHorizontalGroup(
            pelajaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pelajaranPanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pelajaranPanelLayout.setVerticalGroup(
            pelajaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelajaranPanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(635, Short.MAX_VALUE))
        );

        mainPanel.add(pelajaranPanel, "card5");

        siswaPanel.setBackground(new java.awt.Color(236, 240, 241));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Siswa");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addContainerGap(1654, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout siswaPanelLayout = new javax.swing.GroupLayout(siswaPanel);
        siswaPanel.setLayout(siswaPanelLayout);
        siswaPanelLayout.setHorizontalGroup(
            siswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siswaPanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        siswaPanelLayout.setVerticalGroup(
            siswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siswaPanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(635, Short.MAX_VALUE))
        );

        mainPanel.add(siswaPanel, "card6");

        orangTuaPanel.setBackground(new java.awt.Color(236, 240, 241));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Orang Tua Siswa");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addContainerGap(1503, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout orangTuaPanelLayout = new javax.swing.GroupLayout(orangTuaPanel);
        orangTuaPanel.setLayout(orangTuaPanelLayout);
        orangTuaPanelLayout.setHorizontalGroup(
            orangTuaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orangTuaPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        orangTuaPanelLayout.setVerticalGroup(
            orangTuaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangTuaPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(635, Short.MAX_VALUE))
        );

        mainPanel.add(orangTuaPanel, "card7");

        kelasPanel.setBackground(new java.awt.Color(236, 240, 241));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 62, 80));
        jLabel9.setText("Kelas");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addContainerGap(1659, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kelasPanelLayout = new javax.swing.GroupLayout(kelasPanel);
        kelasPanel.setLayout(kelasPanelLayout);
        kelasPanelLayout.setHorizontalGroup(
            kelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kelasPanelLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kelasPanelLayout.setVerticalGroup(
            kelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelasPanelLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(635, Short.MAX_VALUE))
        );

        mainPanel.add(kelasPanel, "card8");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1769, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 2035, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu_pelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_pelajaranActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add panel
        mainPanel.add(pelajaranPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_menu_pelajaranActionPerformed

    private void btn_menu_guru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_guru1ActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add panel
        mainPanel.add(guruPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_menu_guru1ActionPerformed

    private void btn_menu_tingkat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_tingkat1ActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add panel
        mainPanel.add(tingkatPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_menu_tingkat1ActionPerformed

    private void btn_menu_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_siswaActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add panel
        mainPanel.add(siswaPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_menu_siswaActionPerformed

    private void btn_menu_orangtuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_orangtuaActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add panel
        mainPanel.add(orangTuaPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_menu_orangtuaActionPerformed

    private void btn_menu_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_kelasActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add panel
        mainPanel.add(kelasPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_menu_kelasActionPerformed

    private void btn_menu_berandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_berandaActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //add panel
        mainPanel.add(berandaPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_menu_berandaActionPerformed

    private void btn_menu_tentangKamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_tentangKamiActionPerformed
        // TODO add your handling code here:
        AboutView aboutView = new AboutView();
        aboutView.setVisible(true);

    }//GEN-LAST:event_btn_menu_tentangKamiActionPerformed

    private void btn_menu_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_keluarActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Keluar dari Sekolah Apps ? ", "Exit Confirmation", dialogBtn);

        if (dialogResult == 0) {
            //true condition
            System.exit(0);
        } else {
            //false condition
        }
    }//GEN-LAST:event_btn_menu_keluarActionPerformed

    private void btn_guru_tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guru_tambahMouseEntered
        // TODO add your handling code here:
        btn_guru_tambah_div.setBackground(new Color(16, 103, 160));
    }//GEN-LAST:event_btn_guru_tambahMouseEntered

    private void btn_guru_tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guru_tambahMouseExited
        // TODO add your handling code here:
        btn_guru_tambah_div.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_guru_tambahMouseExited

    private void btn_guru_tambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guru_tambahMousePressed
        // TODO add your handling code here:
        btn_guru_tambah_div.setBackground(new Color(0, 77, 134));
    }//GEN-LAST:event_btn_guru_tambahMousePressed

    private void btn_guru_tambah_divMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guru_tambah_divMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guru_tambah_divMouseEntered

    private void btn_guru_tambah_divMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guru_tambah_divMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guru_tambah_divMouseExited

    private void btn_guru_tambah_divMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guru_tambah_divMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guru_tambah_divMousePressed

    private void btn_guru_tambah_divMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guru_tambah_divMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_guru_tambah_divMouseReleased

    private void btn_guru_tambahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guru_tambahMouseReleased
        // TODO add your handling code here:
        btn_guru_tambah_div.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_guru_tambahMouseReleased

    private void btn_guru_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guru_tambahMouseClicked
        // TODO add your handling code here:
        GuruTambahView guruTambah = new GuruTambahView();
        guruTambah.setVisible(true);
    }//GEN-LAST:event_btn_guru_tambahMouseClicked

    private void btn_guru_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guru_refreshActionPerformed
        // TODO add your handling code here:
        tampilGuru();
    }//GEN-LAST:event_btn_guru_refreshActionPerformed

    private void btn_guru_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guru_hapusActionPerformed
        // TODO add your handling code here:
        //deteksi kursor berada di baris berapa
        try {
            db = new Database();
//            mahasiswaTableModel tabelmahasiswa = new mahasiswaTableModel();

            int baris = tblGuru.getSelectedRow();
            String id_guru = (String) tblGuru.getValueAt(baris, 0);
            String nama = (String) tblGuru.getValueAt(baris, 1);
            Object[] pilihan = {"Ya", "Tidak"};
            int jawaban = JOptionPane.showOptionDialog(null, "Anda Yakin Data guru "
                    + "dengan ID Guru " + id_guru + " dengan Nama " + nama + " akan dihapus ?", "Peringatan", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, pilihan, pilihan[0]);
            if (jawaban == 0) {
                db.hapus_guru(id_guru);
                refreshGuru();
            }
        }//end TRY
        catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus !!!");
        }
    }//GEN-LAST:event_btn_guru_hapusActionPerformed

    private void btn_guru_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guru_editActionPerformed
        // TODO add your handling code here:
        guruEdit = new GuruEditView();
//        guruEdit.setVisible(true);

//        lakukan pengecekan data berdasarkan cursor
        int baris = tblGuru.getSelectedRow();
        String id_guru = (String) guruTableModel.getValueAt(baris, 0);
        GuruModel guru = db.pilih_guru(id_guru);

        if (guru != null) {
            guruEdit.setForm(guru);
            guruEdit.setVisible(true);
            refreshGuru();
        } else {
            JOptionPane.showMessageDialog(null, "Guru dengan ID Guru " + id_guru
                    + " tidak ditemukan");
        }

    }//GEN-LAST:event_btn_guru_editActionPerformed

    private void btn_guru_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guru_cariActionPerformed
        // TODO add your handling code here:
        String kataCari = tf_guru_cari.getText().trim();
        if (kataCari != null) {
            guruTableModel.setData(db.cari_nama_guru(kataCari));
            guruTableModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_btn_guru_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel berandaPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btn_guru_cari;
    private javax.swing.JButton btn_guru_edit;
    private javax.swing.JButton btn_guru_hapus;
    private javax.swing.JButton btn_guru_refresh;
    private javax.swing.JLabel btn_guru_tambah;
    private javax.swing.JPanel btn_guru_tambah_div;
    private javax.swing.JButton btn_menu_beranda;
    private javax.swing.JButton btn_menu_guru1;
    private javax.swing.JButton btn_menu_kelas;
    private javax.swing.JButton btn_menu_keluar;
    private javax.swing.JButton btn_menu_orangtua;
    private javax.swing.JButton btn_menu_pelajaran;
    private javax.swing.JButton btn_menu_siswa;
    private javax.swing.JButton btn_menu_tentangKami;
    private javax.swing.JButton btn_menu_tingkat1;
    private javax.swing.JPanel guruPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel kelasPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel orangTuaPanel;
    private javax.swing.JPanel pelajaranPanel;
    private javax.swing.JPanel siswaPanel;
    private javax.swing.JTable tblGuru;
    private javax.swing.JTextField tf_guru_cari;
    private javax.swing.JPanel tingkatPanel;
    // End of variables declaration//GEN-END:variables

}
